name: pre-commit

on:
  pull_request:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.1

  testing:
    runs-on: ${{ matrix.os }}
